apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: graphip
spec:
  selector:
    matchLabels:
      app: graphip
  replicas: 1
  template:
    metadata:
      labels:
        app: graphip
        env: development
    spec:
      imagePullSecrets:
        - name: gitlab-private-registry
      containers:
      - name: graphip
        image: registry.gitlab.com/graphip/node-server:0.0.3-node
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: graphip-config
        - secretRef:
            name: graphip-secret
