apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: graphip
spec:
  selector:
    matchLabels:
      app: graphip
  replicas: 1
  template:
    metadata:
      labels:
        app: graphip
        env: development
    spec:
      imagePullSecrets:
        - name: gitlab-private-registry
      containers:
      - name: graphip
        image: registry.gitlab.com/graphip/node-server:v0.2.0
        readinessProbe:
          httpGet:
            path: /health
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: graphip-config
        - secretRef:
            name: graphip-secret
      - image: postgres:12
        imagePullPolicy: "IfNotPresent"
        name: postgres
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
      # [END proxy_container]
      # [START volumes]
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      # [END volumes]